config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {       # ← 恐らく最初は”devise_for:”のみの記載かと
    registrations: "users/registrations"
  }
  resources :users, only: [:index, :show]
  root to: 'articles#top'
  get 'tags/:tag_name', to: 'articles#index', as: :tag
  resources :articles do
    resources :likes, only: [:create, :destroy]
  end
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_rich_text :content
    validates :title, presence: true, length: { maximum: 30 }
    belongs_to :user
    has_many :likes
    has_many :liked_users, through: :likes, source: :user

    # acts_as_taggable_on :tagのエイリアス
    acts_as_taggable

    def self.ransackable_attributes(auth_object = nil)
        %w[title created_at]
    end

    def self.ransackable_associations(auth_object = nil)
        []
    end

    scope :recent, -> { order(created_at: :desc) }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :article
  belongs_to :user
  validates_uniqueness_of :article_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable
  has_many :articles,  dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_articles, through: :likes, source: :article

  def already_liked?(article)
    self.likes.exists?(article_id: article.id)
  end

  validates :name, presence: true
  validates :email, uniqueness: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # CSRFトークンの含まれない悪意あるPOSTリクエストに対してエラーを吐く
    protect_from_forgery with: :exception
    # デバイスのコントローラーに限り、下記に定義したストロングパラメーターを反映させる
    before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
        articles_path # ログイン後に遷移するpathを設定
    end

    def after_sign_out_path_for(resource)
        new_user_session_path # ログアウト後に遷移するpathを設定
    end

    private

    def sign_in_required
        redirect_to new_user_session_url unless user_signed_in?
    end

    protected

    def configure_permitted_parameters
        added_attrs = [ :name,:username, :email, :password, :password_confirmation　]
        devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
        devise_parameter_sanitizer.permit :account_update, keys: added_attrs
        devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:top]
  before_action :sign_in_required, except: [:top]

  def top
  end

  def index
    @q = current_user.articles.ransack(params[:q])
    @articles = @q.result(distinct: true)
    @articles = Article.all.page(params[:page]).per(5)
    # コントローラーでパラメーターを受け取る
    # tagged_with("タグ名")で絞り込み処理をする
    if params[:tag_name]
      @articles = Article.tagged_with("#{params[:tag_name]}").all.page(params[:page]).per(5)
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.new(article_params)

    if @article.save
      redirect_to articles_url, notice: "記事「#{@article.title}」を登録しました。"
    else
      render :new
    end
  end

  def show
    @article = current_user.articles.find(params[:id])
    @like = Like.new
  end

  def edit
    @article = current_user.articles.find(params[:id])
  end

  def update
    @article = current_user.articles.find(params[:id])

    if @article.update(article_params)
      redirect_to articles_url, notice: "記事「#{@article.title}」を更新しました"
    else
      render :edit
    end
  end

  def destroy
    article = current_user.articles.find(params[:id])
    article.destroy
    redirect_to articles_url, notice: "記事「#{article.title}」を削除しました。"
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :tag_list)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :set_article, only: [:create, :destroy]
    def create
        @like = current_user.likes.create(article_id: params[:article_id])
        redirect_to article_path(@article)
    end

    def destroy
        @like = Like.find_by(article_id: params[:article_id], user_id: current_user.id)
        @like.destroy
        redirect_to article_path(@article)
    end

    private
    def set_article
        @article = Article.find(params[:article_id])
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController #deviseの該当クラスを継承する
  def create
    super do                                             # deviseの他の機能は維持したまま
      resource.update(confirmed_at: Time .now.utc)       # skip_confirmation!と同一処理を行い自動で認証をクローズする
    end
  end

  # アカウント情報変更後、記事一覧にリダイレクトさせる
  def after_update_path_for(resource)
    articles_path(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.slim
figure class=("attachment attachment--#{blob.representable? ? "preview" : "file"} attachment--#{blob.filename.extension}")
  - if blob.representable?
    = image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ])
  figcaption.attachment__caption
    - if caption = blob.try(:caption)
      = caption
    - else
      span.attachment__name= blob.filename
      span.attachment__size= number_to_human_size blob.byte_size

app/views/articles/_form.html.slim
- if article.errors.present?
  ul#error_explanation
    - article.errors.full_messages.each do |message|
      li = javascript_tag "M.toast({html: '#{message}',
                             displayLength: 4000,
                             inDuration: 400,
                             outDuration: 800})"
div.row.col.s12
= form_with model: @article, local: true do |f|
  div
    = f.label :title
    = f.text_field :title, id: 'article_title'
  div
    = f.label :content
    = f.rich_text_area :content, id: 'article_content'
  / 記事投稿フォームにタグを入力できるようにする
  / 入力されたタグが配列としてtag_listに代入される
  div
    = f.label :tag_list
    = f.text_field :tag_list, value: @article.tag_list.join(','), class: "form-control"
  button class="btn waves-effect waves-light yellow darken-1" type="submit" name="action" submit
    <i class="material-icons right">send</i>

app/views/articles/_tag_list.html.slim
/ 受け取ったパラメーターを一つ一つ分けて表示する
/ タグにリンクを付け、リンク先にパラメーターを渡す
- tag_list.each do |tag|
  span
    = link_to tag, articles_path(tag_name: tag), class: "waves-effect waves-light btn blue-grey lighten-4"

app/views/articles/edit.html.slim
h3.yellow-text.text-darken-1　タスクの編集

= render partial: 'form', locals: { article: @article }

app/views/articles/index.html.slim
h3.yellow-text.text-darken-1　記事一覧

= search_form_for @q do |f|
  = f.label :title_cont, '名称'
    = f.search_field :title_cont
  = f.label :created_at_gteq, '登録日時'
    = f.search_field :created_at_gteq
  button class="btn waves-effect waves-light yellow darken-1" type="submit" name="action" 検索
    <i class="material-icons right">search</i>

table.card-panel.hoverable
  thead
    tr
      th= sort_link(@q, :title)
      th class="created_at" = Article.human_attribute_name(:created_at)
      th class="tag" = Article.human_attribute_name(:tag_list)
      th
      th= Article.human_attribute_name(:liked_count)

  tbody
    - @articles.each do |article|
      tr
        td class="show_link" = link_to article.title, article
        td= article.created_at
        / タグ表示欄の追加
        / renderを利用し、パーシャルファイルで処理
        / tag_listをメソッドとして使用し、tag_listにarticle.tag_listで取り出したパラメーターを渡す
        td= render 'articles/tag_list', tag_list: article.tag_list
        td
          = link_to '編集', edit_article_path(article), class: "waves-effect waves-light btn yellow darken-1"
          = link_to '削除', article, method: :delete, data: { confirm: "記事「#{article.title}」を削除します。よろしいですか？" }, class: "waves-effect waves-light btn yellow darken-1"
        td class="liked" = article.liked_users.count

= paginate @articles

app/views/articles/new.html.slim
h3.yellow-text.text-darken-1　新規登録

= render partial: 'form', locals: { article: @article }

app/views/articles/show.html.slim
h3.yellow-text.text-darken-1　記事詳細

table.card-panel.hoverable
  tbody
    tr
      th= Article.human_attribute_name(:id)
      td= @article.id
    tr
      th= Article.human_attribute_name(:title)
      td= @article.title
    tr
      th= Article.human_attribute_name(:content)
      td= simple_format(h(@article.content), {}, sanitize: false, wrapper_tag: "div")
    tr
      th= Article.human_attribute_name(:tag_list)
      td= render 'articles/tag_list', tag_list: @article.tag_list
    tr
      th= Article.human_attribute_name(:created_at)
      td= @article.created_at
    tr
      th= Article.human_attribute_name(:updated_at)
      td= @article.updated_at
h5.grey-text.text-darken-2
  | いいね数：
  = @article.likes.count
- if current_user.already_liked?(@article)
  = link_to 'いいねを取り消す', article_like_path(@article), method: :delete, class: 'waves-effect waves-light btn blue lighten-1'
- else
  = link_to 'いいね', article_likes_path(@article), method: :post, class: 'waves-effect waves-light btn pink lighten-2'
h5.grey-text.text-darken-2
  | いいねしたユーザー
- @article.liked_users.each do |user|
  li
    = user.email

= link_to '編集', edit_article_path, class: "waves-effect waves-light btn yellow darken-1"
= link_to '削除', @article, method: :delete, data: { confirm: "記事「#{@article.title}」を削除します。よろしいですか？" }, class: "waves-effect waves-light btn yellow darken-1"

app/views/articles/top.html.slim
// jsファイルを読み込む
= javascript_include_tag 'article_js'

// 背景画像を切り替える関数を呼び出しブラウザへ表示する
.clImg
  h1 class="kinniku" style="background-image:url(#{asset_path "kinniku.jpg"})" ０円で作り上げる筋肉
  h1 class="kinniku_2" style="background-image:url(#{asset_path "kinniku_2.jpg"})"  ０円で作り上げる筋肉
  h1 class="kinniku_3" style="background-image:url(#{asset_path "kinniku_3.jpg"})"  ０円で作り上げる筋肉

app/views/layouts/_toast.html.slim
- flash.each do |type, msg|
  - color = 'grey.darken-3' if type == 'notice'
  - color = 'red lighten-1' if type == 'alert'

  = javascript_tag "M.toast({html: '#{msg}',
                             classes: '#{color}',
                             displayLength: 4000,
                             inDuration: 400,
                             outDuration: 800})"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | TestApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body
    header
      nav.grey.darken-3
        div class="nav-wrapper"
            div link_to="/" class="brand-logo"　NonGym
            - if user_signed_in?
              ul id="nav-mobile" class="right hide-on-med-and-down"
                li
                  = link_to 'プロフィール変更', edit_user_registration_path
                li
                  = link_to 'ログアウト', destroy_user_session_path, method: :delete
                li
                  a href="/articles/new"  新規登録
                li
                  a href="/articles"  記事一覧
            - else
              ul id="nav-mobile" class="right hide-on-med-and-down"
                li
                  = link_to 'サインアップ', new_user_registration_path
                li
                  = link_to 'ログイン', new_user_session_path
    = render partial: 'layouts/toast'
    = yield

app/views/users/index.html.slim
h1 Users#index
p Find me in app/views/users/index.html.slim

app/views/users/show.html.slim
h1 Users#show
p Find me in app/views/users/show.html.slim